# SKIP=<id> <id> git commit -m "foo"
# git commit -m "bar" --no-verify #skip all
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0 # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
    hooks:
      -  id: trailing-whitespace
      -  id: end-of-file-fixer
      -  id: check-docstring-first
      -  id: check-json
      -  id: check-added-large-files
      -  id: check-yaml
      -  id: pretty-format-json
      -  id: detect-aws-credentials
      -  id: detect-private-key
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.30.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
#       - id: terraform_tfsec
      - id: terraform_validate
      - id: terraform_fmt
    #   - id: terraform_docs
    # args:
    #   - --hook-config=--path-to-file=README.md        # Valid UNIX path. I.e. ../TFDOC.md or docs/README.md etc.
    #   - --hook-config=--add-to-existing-file=true     # Boolean. true or false
    #   - --hook-config=--create-file-if-not-exist=true # Boolean. true or false
  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.16
    hooks:
#       - id: circleci-config-validate
      - id: forbid-binary
#      - id: go-fmt
#       - id: go-test
#      - id: go-mod-tidy
#      - id: go-generate
#       - id: shellcheck
#       - id: shfmt
